version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: alam
      MYSQL_DATABASE: express
    ports:
      - "3306:3306"

  springboot-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/express
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: alam
